"""empty message

Revision ID: 15f210519ebf
Revises: 7558271d7076
Create Date: 2026-08-15 15:31:16.370324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15f210519ebf'
down_revision: Union[str, Sequence[str], None] = '7558271d7076'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('senha_hash', sa.String(length=255), nullable=False))
    op.drop_column('usuarios', 'senha_has')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('senha_has', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('usuarios', 'senha_hash')
    # ### end Alembic commands ###
