"""empty message

Revision ID: 7558271d7076
Revises: 
Create Date: 2026-08-15 15:20:51.865776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7558271d7076'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.Column('senha_has', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('endereco_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rua', sa.String(length=30), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('bairro', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=10), nullable=False),
    sa.Column('pais', sa.String(length=10), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orcamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.Column('valor_total_juros', sa.Float(), nullable=False),
    sa.Column('valor_parcela', sa.Float(), nullable=False),
    sa.Column('valor_entrada', sa.Float(), nullable=False),
    sa.Column('quantidade_parcela', sa.Integer(), nullable=False),
    sa.Column('taxa_juros', sa.Float(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_validade', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.Float(precision=50), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status_orcamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pendente', sa.String(length=20), nullable=False),
    sa.Column('aprovado', sa.String(length=20), nullable=False),
    sa.Column('reprovado', sa.String(length=20), nullable=False),
    sa.Column('expirado', sa.String(length=20), nullable=False),
    sa.Column('orcamento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status_orcamento')
    op.drop_table('produto')
    op.drop_table('orcamento')
    op.drop_table('endereco_usuario')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
